/**:
  ros__parameters:
    additional_lidars: []
    ransac_input_topics: [
      "/sensing/lidar/front_center/pointcloud"
    ]
    use_single_frame_filter: True
    use_time_series_filter: False

    common_crop_box_filter:
      parameters:
        min_x: -100.0
        max_x: 150.0
        min_y: -70.0
        max_y: 70.0
        margin_max_z: 0.0  # to extend the crop box max_z from vehicle_height
        margin_min_z: -2.5 # to extend the crop box min_z from ground
        negative: False

    common_ground_filter:
      plugin: "ground_segmentation::ScanGroundFilterComponent"
      parameters:
        global_slope_max_angle_deg: 10.0
        local_slope_max_angle_deg: 13.0 # recommended 30.0 for non elevation_grid_mode
        split_points_distance_tolerance: 0.2
        use_virtual_ground_point: True
        split_height_distance: 0.2
        non_ground_height_threshold: 0.20
        grid_size_m: 0.5
        grid_mode_switch_radius: 20.0
        gnd_grid_buffer_size: 4
        detection_range_z_max: 2.5
        elevation_grid_mode: true

    # common_ground_filter:
    #   plugin: "ground_segmentation::RayGroundFilterComponent"
    #   parameters:
    #     min_x: -0.01
    #     max_x: +0.01
    #     min_y: -0.01
    #     max_y: +0.01
    #     use_vehicle_footprint: True
    #     general_max_slope: 10.0
    #     local_max_slope: 10.0
    #     initial_max_slope: 10.0
    #     radial_divider_angle: 1.0
    #     min_height_threshold: 0.3
    #     concentric_divider_distance: 0.0
    #     reclass_distance_threshold: 0.1

    short_height_obstacle_detection_area_filter:
      parameters:
        min_x: 0.0
        max_x: 21.6  # max_x: 20.0m + base_link2xt32_front_center distance 1.6m
        min_y: -4.0
        max_y: 4.0
        min_z: -0.5
        max_z: 0.5
        negative: False

    ransac_ground_filter:
      parameters:
#        base_frame: base_link
        unit_axis: "z"
        max_iterations: 50
        min_trial: 200
        min_points: 400
        outlier_threshold: 0.1
        plane_slope_threshold: 10.0
        voxel_size_x: 0.1
        voxel_size_y: 0.1
        voxel_size_z: 0.1
        height_threshold: 0.10
        debug: False
