/**:
  ros__parameters:
    point_filters: |
      {
        "ring_section_filter": [
        [0, 0, 360],
        [3, 0, 360],
        [6, 0, 360],
        [9, 0, 360],
        [12, 0, 360],
        [15, 0, 360],
        [18, 0, 360],
        [21, 0, 360],
        [24, 0, 360],
        [27, 0, 360],
        [30, 0, 360],
        [33, 0, 360],
        [36, 0, 360],
        [39, 0, 360],
        [42, 0, 360],
        [45, 0, 360],
        [48, 0, 360],
        [51, 0, 360],
        [54, 0, 360],
        [57, 0, 360],
        [60, 0, 360],
        [63, 0, 360],
        [66, 0, 360],
        [69, 0, 360],
        [72, 0, 360],
        [75, 0, 360],
        [78, 0, 360],
        [81, 0, 360],
        [84, 0, 360],
        [87, 0, 360],
        [90, 0, 360],
        [93, 0, 360],
        [96, 0, 360],
        [99, 0, 360],
        [102, 0, 360],
        [105, 0, 360],
        [108, 0, 360],
        [111, 0, 360],
        [114, 0, 360],
        [117, 0, 360],
        [120, 0, 360],
        [123, 0, 360],
        [126, 0, 360]
        ]
      }
