# Description:
#   name: diag name
#   is_active: Force update or not
#   status: diag status set by dummy diag publisher "OK, Warn, Error, Stale"
#
# Note:
#
# default values are:
#   is_active: "true"
#   status: "OK"
---
/**:
  ros__parameters:
    required_diags:
      # gnss
      gnss_connection: default
      gnss_data: default
      gnss_antenna: default
      gnss_tx_usage: default
      gnss_spoofing: default
      gnss_jamming: default
      fix topic status: default

      # velodyne
      velodyne_connection: default
      velodyne_temperature: default
      velodyne_rpm: default
