# Description:
#   name: diag name
#   is_active: Force update or not
#   status: diag status set by dummy diag publisher "OK, Warn, Error, Stale"
#
# Note:
#
# default values are:
#   is_active: "true"
#   status: "OK"
---
/**:
  ros__parameters:
    required_diags:
      # node_alive_monitoring
      "topic_status: sensing_topic_status": default

      # performance monitoring
      "blockage: blockage_validation": default

      # velodyne
      "connection: velodyne_connection": default
      "temperature: velodyne_temperature": default
      "rpm: velodyne_rpm": default

      # gnss
      "connection: gnss_connection": default
      "data: gnss_data": default
      "antenna: gnss_antenna": default
      "tx_usage: gnss_tx_usage": default
      "spoofing: gnss_spoofing": default
      "jamming: gnss_jamming": default
      "fix_topic_status: fix topic status": default

      # imu
      "gyro_bias_validator: gyro_bias_validator": default