/**:
  ros__parameters:
    sensing:
      type: diagnostic_aggregator/AnalyzerGroup
      path: sensing
      analyzers:
        node_alive_monitoring:
          type: diagnostic_aggregator/AnalyzerGroup
          path: node_alive_monitoring
          analyzers:
            topic_status:
              type: diagnostic_aggregator/GenericAnalyzer
              path: topic_status
              contains: [": sensing_topic_status"]
              timeout: 1.0

        lidar:
          type: diagnostic_aggregator/AnalyzerGroup
          path: lidar
          analyzers:
            performance_monitoring:
              type: diagnostic_aggregator/AnalyzerGroup
              path: performance_monitoring
              analyzers:
                blockage:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: blockage
                  contains: [": blockage_validation"]
                  timeout: 1.0
            velodyne:
              type: diagnostic_aggregator/AnalyzerGroup
              path: velodyne
              analyzers:
                health_monitoring:
                  type: diagnostic_aggregator/AnalyzerGroup
                  path: health_monitoring
                  analyzers:
                    connection:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: connection
                      contains: [": velodyne_connection"]
                      timeout: 3.0

                    temperature:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: temperature
                      contains: [": velodyne_temperature"]
                      timeout: 3.0

                    rpm:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: rpm
                      contains: [": velodyne_rpm"]
                      timeout: 3.0

        gnss:
          type: diagnostic_aggregator/AnalyzerGroup
          path: gnss
          analyzers:
            health_monitoring:
              type: diagnostic_aggregator/AnalyzerGroup
              path: health_monitoring
              analyzers:
                connection:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: connection
                  contains: [": gnss_connection"]
                  timeout: 3.0

                data:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: data
                  contains: [": gnss_data"]
                  timeout: 3.0

                antenna:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: antenna
                  contains: [": gnss_antenna"]
                  timeout: 3.0

                tx_usage:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: tx_usage
                  contains: [": gnss_tx_usage"]
                  timeout: 3.0

                spoofing:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: spoofing
                  contains: [": gnss_spoofing"]
                  timeout: 3.0

                jamming:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: jamming
                  contains: [": gnss_jamming"]
                  timeout: 3.0

                fix_topic_status:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: fix_topic_status
                  contains: [": fix topic status"]
                  timeout: 3.0

        imu:
          type: diagnostic_aggregator/AnalyzerGroup
          path: imu
          analyzers:
            bias_monitoring:
              type: diagnostic_aggregator/AnalyzerGroup
              path: bias_monitoring
              analyzers:
                gyro_bias_validator:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: gyro_bias_validator
                  contains: [": gyro_bias_validator"]
                  timeout: 1.0
