front_unit_base_link:
  pandar_40p_front_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 1.570796
  pandar_qt_front_base_link:
    x: 0.019
    y: 0.0
    z: 0.136
    roll: 0.0
    pitch: 0.0
    yaw: 2.09439
  camera6/camera_link:
    x: 0.0534
    y: 0.0
    z: 0.2657
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  front_center/radar_link:
    x: -0.01295
    y: 0.0
    z: -0.07554
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  front_left/radar_link:
    x: -0.132
    y: 1.0 # todo
    z: 0.0174
    roll: 0.0
    pitch: 0.0
    yaw: 1.2217 # 70[deg]
  front_right/radar_link:
    x: -0.132
    y: -1.0 # todo
    z: 0.0174
    roll: 0.0
    pitch: 0.0
    yaw: -1.2217 # 70[deg]
