base_link:
  top_unit_base_link:
    x: 4.6621
    y: 1.079
    z: 2.8087
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  front_unit_base_link:
    x: 5.6221
    y: 0.0
    z: 0.7547
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  rear_unit_base_link:
    x: -1.4271
    y: 0.0
    z: 0.4795
    roll: 0
    pitch: 0
    yaw: -3.141500
  gnss_link:
    x: -0.3
    y: 0.0
    z: 2.689
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
