base_link:
  sensor_kit_base_link:
    x: 4.66244
    y: 1.07589
    z: 2.78926
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  # radar
  ars548/front_center/radar_link:
    x: 5.69207
    y: 0.0
    z: 0.78894
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
