base_link:
  sensor_kit_base_link:
    x: 4.66244
    y: 1.07589
    z: 2.78926
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  # radar
  ars548/front_center/radar_link:
    x: 5.69207
    y: 0.0
    z: 0.78894
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  ars548/front_left/radar_link:
    x: 5.37204
    y: 1.08537
    z: 0.73431
    roll: 0.0
    pitch: 0.0
    yaw: 1.2211 # 70 [deg]

  ars548/front_right/radar_link:
    x: 5.37204
    y: -1.06642
    z: 0.73431
    roll: 0.0
    pitch: 0.0
    yaw: -1.2211 # 70 [deg]

  ars548/rear_center/radar_link:
    x: -1.50704
    y: 0.0
    z: 0.78894
    roll: 0.0
    pitch: 0.0
    yaw: 3.141592 # 180 [deg]

  ars548/rear_left/radar_link:
    x: -1.27564
    y: 1.07767
    z: 0.5487
    roll: 0.0
    pitch: 0.0
    yaw: 1.9189 # 110 [deg]

  ars548/rear_right/radar_link:
    x: -1.27564
    y: -1.07768
    z: 0.5487
    roll: 0.0
    pitch: 0.0
    yaw: -1.9189 # 110 [deg]
