sensor_kit_base_link:
  # left upper
  pandar/top_left/lidar_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 1.570796 # 90 [deg]
  pandar/top_left_bottom/lidar_link:
    x: 0.0
    y: -0.025
    z: -0.115
    roll: 0.0
    pitch: 0.6981 # 40[deg]
    yaw: 1.570796 # 90 [deg]
  camera/top_left_front/camera_link:
    x: 0.12758
    y: -0.04589
    z: -0.0866
    roll: 0.0
    pitch: 0.08722 # 5 [deg]
    yaw: 0.85478 # 49 [deg]
  camera/top_left_rear/camera_link:
    x: -0.12842
    y: -0.04589
    z: -0.0866
    roll: 0.0
    pitch: 0.08722 # 5 [deg]
    yaw: 2.2678 # 130 [deg]
  camera/top_left_center/camera_link:
    x: 0.0
    y: -0.04089
    z: -0.18666
    roll: 0.0
    pitch: 0.933278 # 53.50 [deg]
    yaw: 1.570796 # 90 [deg]

  # right upper
  pandar/top_right/lidar_link:
    x: 0.0
    y: -2.15178
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: -1.570796 # -90 [deg]
  pandar/top_right_bottom/lidar_link:
    x: 0.0
    y: -2.12678
    z: -0.115
    roll: 0.0
    pitch: 0.6981 # 40 [deg]
    yaw: -1.570796 # -90 [deg]
  camera/top_right_front/camera_link:
    x: 0.12758
    y: -2.10589
    z: -0.0866
    roll: 0.0
    pitch: 0.08722 # 5 [deg]
    yaw: -0.85478 # -49 [deg]
  camera/top_right_rear/camera_link:
    x: -0.12842
    y: -2.10589
    z: -0.0866
    roll: 0.0
    pitch: 0.08722 # 5 [deg]
    yaw: -2.2678 # -130 [deg]
  camera/top_right_center/camera_link:
    x: 0.0
    y: -2.11089
    z: -0.18666
    roll: 0.0
    pitch: 0.933278 # 53.50 [deg]
    yaw: -1.570796 # -90 [deg]

  # front upper
  tamagawa/left/imu_link:
    x: 0.562
    y: -0.99974
    z: -0.06146
    roll: 3.141592
    pitch: 0.0
    yaw: 0.0
  tamagawa/right/imu_link:
    x: 0.562
    y: -1.13974
    z: -0.06146
    roll: 3.141592
    pitch: 0.0
    yaw: 0.0
  camera/front_center/camera_link:
    x: 0.73758
    y: -1.26439
    z: -0.06666
    roll: 0.0
    pitch: 0.8373 # 48 [deg]
    yaw: 0.0
  camera/top_front/c2-030/camera_link:
    x: 0.73058
    y: -1.18899
    z: -0.02166
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera/top_front/c2-120/camera_link:
    x: 0.73058
    y: -1.03819
    z: -0.02166
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera/top_front/c2-062/camera_link:
    x: 0.73058
    y: -0.96279
    z: -0.02166
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  # front lower

  # rear lower

  # GNSS
