top_unit_base_link:
  camera0/camera_link:
    x: 0.76673
    y: -1.186
    z: 0.05965
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera1/camera_link:
    x: 0.16818
    y: -2.10372
    z: -0.0651
    roll: 0.0
    pitch: 0.22689 # 13[deg]
    yaw: -1.134464 # 65[deg]
  camera2/camera_link:
    x: -0.19012
    y: -2.09141
    z: -0.0651
    roll: 0.0
    pitch: 0.22689 # 13[deg]
    yaw: -2.39110 # 137[deg]
  camera4/camera_link:
    x: -0.19012
    y: -0.06258
    z: -0.0651
    roll: 0.0
    pitch: 0.22689 # 13[deg]
    yaw: 2.39110 # 137[deg]
  camera5/camera_link:
    x: 0.16818
    y: -0.05027
    z: -0.0651
    roll: 0.000000
    pitch: 0.22689 # 13[deg]
    yaw: 1.134464 # 65[deg]
  camera7/camera_link:
    x: 0.76673
    y: -0.964
    z: 0.05965
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  pandar_40p_left_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 3.141592
  pandar_qt_left_base_link:
    x: 0.0
    y: -0.04
    z: -0.17
    roll: 0.6981 # 40[deg]
    pitch: 0.0
    yaw: -3.141592
  pandar_40p_right_base_link:
    x: 0.000000
    y: -2.154
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  pandar_qt_right_base_link:
    x: 0.0
    y: -2.114
    z: -0.17
    roll: 0.6981 # 40[deg]
    pitch: 0.0
    yaw: 0.0
  tamagawa/imu_link:
    x: 0.5675
    y: 0.0
    z: -0.0651
    roll: 3.141592
    pitch: 0.0
    yaw: 0.0
