launches:
  - sensor_type: velodyne_VLS128
    namespace: top
    parameters:
      max_range: 250.0
      sensor_frame: velodyne_top
      sensor_ip: 192.168.1.201
      data_port: 2368
      scan_phase: 300.0
      vertical_bins: 128
      horizontal_ring_id: 64
      horizontal_resolution: 0.4
      is_channel_order_top2down: false
  - sensor_type: velodyne_VLP16
    namespace: left
    parameters:
      max_range: 5.0
      sensor_frame: velodyne_left
      sensor_ip: 192.168.1.202
      data_port: 2369
      scan_phase: 180.0
      cloud_min_angle: 300
      cloud_max_angle: 60
      vertical_bins: 16
      horizontal_ring_id: 0
      horizontal_resolution: 0.4
      is_channel_order_top2down: false
  - sensor_type: velodyne_VLP16
    namespace: right
    parameters:
      max_range: 5.0
      sensor_frame: velodyne_right
      sensor_ip: 192.168.1.203
      data_port: 2370
      scan_phase: 180.0
      cloud_min_angle: 300
      cloud_max_angle: 60
      vertical_bins: 16
      horizontal_ring_id: 0
      horizontal_resolution: 0.4
      is_channel_order_top2down: false
  - sensor_type: velodyne_VLP16
    namespace: rear
    parameters:
      max_range: 1.5
      sensor_frame: velodyne_rear
      sensor_ip: 192.168.1.204
      data_port: 2371
      scan_phase: 180.0
      cloud_min_angle: 300
      cloud_max_angle: 60
      vertical_bins: 16
      horizontal_ring_id: 0
      horizontal_resolution: 0.4
      is_channel_order_top2down: false

preprocessor:
  input_topics:
    - /sensing/lidar/top/pointcloud
    - /sensing/lidar/left/pointcloud
    - /sensing/lidar/right/pointcloud
    - /sensing/lidar/rear/pointcloud
  input_offset:
    - 0.035
    - 0.025
    - 0.025
    - 0.025
  timeout_sec: 0.095
  input_twist_topic_type: twist
  publish_synchronized_pointcloud: false
