

# Configuration Settings for the Rover Rx

/**:
  ros__parameters:
    device: tcp://192.168.100.101:28784

    frame_id: gnss_right_link

    datum: WGS84

    poi_to_arp:
      delta_e: 0.0
      delta_n: 0.0
      delta_u: 0.0

    att_offset:
      heading: 0.0
      pitch: 0.0

    ant_type: Unknown
    ant_serial_nr: Unknown

    polling_period:
      pvt: 200
      rest: 200

    use_gnss_time: false
    leap_seconds: 18

    publish:
      navsatfix: true
      gpsfix: false
      gpgga: false
      gprmc: false
      gpst : false
      measepoch: false
      pvtcartesian: false
      pvtgeodetic: true
      poscovcartesian: false
      poscovgeodetic: true
      velcovgeodetic: false
      atteuler: false
      attcoveuler: false
      pose: false
      diagnostics: true
      # For GNSS Rx only
      gpgsa: false
      gpgsv: false
      # For INS Rx only
      insnavcart: false
      insnavgeod: false
      extsensormeas: false
      imusetup: false
      velsensorsetup: false
      exteventinsnavcart: false
      exteventinsnavgeod: false
      imu: false
      localization: false
      tf: false
