base_link:
  sensor_kit_base_link:
    x: 7.3618
    y: 1.2200
    z: 3.1790
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  # radar
  front_center/radar_link:
    x: 8.4640
    y: 0.0
    z: 0.6398
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  front_left/radar_link:
    x: 8.0452
    y: 1.2444
    z: 0.5947
    roll: 0.0
    pitch: 0.0
    yaw: 1.2211 # 70 [deg]

  front_right/radar_link:
    x: 8.0452
    y: -1.2444
    z: 0.5947
    roll: 0.0
    pitch: 0.0
    yaw: -1.2211 # 70 [deg]

  rear_center/radar_link:
    x: -2.7802
    y: 0.0
    z: 0.8283
    roll: 0.0
    pitch: 0.0
    yaw: 3.141592 # 180 [deg]

  rear_left/radar_link:
    x: -2.5859
    y: 1.2417
    z: 0.7591
    roll: 0.0
    pitch: 0.0
    yaw: 1.9189 # 110 [deg]

  rear_right/radar_link:
    x: -2.5859
    y: -1.2417
    z: 0.7591
    roll: 0.0
    pitch: 0.0
    yaw: -1.9189 # 110 [deg]
