/**:
  ros__parameters:
    host_ip: 10.13.1.166
    sensor_ip: 10.13.1.114
    data_port: 42102
    base_frame: base_link
    object_frame: base_link
    launch_hw: true
    multicast_ip: 224.0.2.2
    sensor_model: ARS548
    configuration_host_port: 42401
    configuration_sensor_port: 42101
    use_sensor_time: false
    configuration_vehicle_length: 7.2369
    configuration_vehicle_width: 2.2916
    configuration_vehicle_height: 3.08
    configuration_vehicle_wheelbase: 4.76012
