/**:
  ros__parameters:
    debug_mode: false
    has_static_tf_only: false
    rosbag_length: 10.0
    maximum_queue_size: 5
    timeout_sec: 0.2
    is_motion_compensated: false
    publish_synchronized_pointcloud: false
    keep_input_frame_in_synchronized_pointcloud: true
    publish_previous_but_late_pointcloud: false
    synchronized_pointcloud_postfix: pointcloud
    input_twist_topic_type: twist
    input_topics: [
                    "/sensing/lidar/left_lower/pointcloud_before_sync",
                    "/sensing/lidar/left_upper/pointcloud_before_sync",
                    "/sensing/lidar/front_lower/pointcloud_before_sync",
                    "/sensing/lidar/front_upper/pointcloud_before_sync",
                    "/sensing/lidar/right_upper/pointcloud_before_sync",
                    "/sensing/lidar/right_lower/pointcloud_before_sync",
                    "/sensing/lidar/rear_lower/pointcloud_before_sync",
                    "/sensing/lidar/rear_upper/pointcloud_before_sync"
                ]
    output_frame: base_link
    matching_strategy:
      type: advanced
      lidar_timestamp_offsets: [0.0, 0.0, 0.025, 0.028, 0.026, 0.05, 0.075, 0.076]
      lidar_timestamp_noise_window: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
