/**:
  ros__parameters:
    point_filters: |
      {
        "ring_section_filter": [
          [0, 0, 360],
          [1, 0, 360],
          [2, 0, 360],
          [3, 0, 360],
          [4, 0, 360],
          [5, 0, 360],
          [6, 0, 360],
          [7, 0, 360],
          [8, 0, 360],
          [9, 0, 360],
          [10, 0, 360],
          [11, 0, 360],
          [12, 0, 360],
          [13, 0, 360],
          [14, 0, 360],
          [15, 0, 360],
          [16, 0, 360],
          [17, 0, 360],
          [18, 0, 360],
          [19, 0, 360],
          [20, 0, 360],
          [21, 0, 360],
          [22, 0, 360],
          [23, 0, 360],
          [24, 0, 360],
          [25, 0, 360],
          [26, 0, 360],
          [27, 0, 360],
          [28, 0, 360],
          [29, 0, 360],
          [30, 0, 360],
          [31, 0, 360],
          [32, 0, 360],
          [33, 0, 360],
          [34, 0, 360],
          [35, 0, 360],
          [36, 0, 360],
          [37, 0, 360],
          [38, 0, 360],
          [39, 0, 360],
          [40, 0, 360],
          [41, 0, 360],
          [42, 0, 360],
          [43, 0, 360],
          [44, 0, 360],
          [45, 0, 360],
          [46, 0, 360],
          [47, 0, 360],
          [48, 0, 360],
          [49, 0, 360],
          [50, 0, 360],
          [51, 0, 360],
          [52, 0, 360],
          [53, 0, 360],
          [54, 0, 360],
          [55, 0, 360],
          [56, 0, 360],
          [57, 0, 360],
          [58, 0, 360],
          [59, 0, 360],
          [50, 0, 360],
          [51, 0, 360],
          [52, 0, 360],
          [53, 0, 360],
          [54, 0, 360],
          [55, 0, 360],
          [56, 0, 360],
          [57, 0, 360],
          [58, 0, 360],
          [59, 0, 360],
        ]
      }
