/**:
  ros__parameters:
    point_filters: |
      {
        "ring_section_filter": [
        [71, 36, 39],
        [72, 36, 39],
        [73, 36, 39],
        [74, 36, 41],
        [75, 36, 41],
        [76, 36, 41],
        [77, 34, 41],
        [77, 34, 41],
        [78, 33, 41],
        [79, 33, 41],
        [80, 33, 41],
        [81, 33, 41],
        [82, 33, 41],
        [83, 33, 41],
        [84, 33, 40],
        [85, 33, 40],
        [86, 33, 39],
        [87, 33, 39],
        [88, 34, 37],
        [88, 36, 37],
        [88, 35, 37]
        ]
      }
