# Description:
#   name: diag name
#   is_active: Force update or not
#   status: diag status set by dummy diag publisher "OK, Warn, Error, Stale"
#
# Note:
#
# default values are:
#   is_active: "true"
#   status: "OK"
---
/**:
  ros__parameters:
    required_diags:
      # gnss
      ## /sensing/gnss/001-connection
      "topic_state_monitor_gnss_pose: gnss_topic_status": default

      ## /sensing/gnss/002-quality
      "septentrio_driver: Quality indicators": default

      # imu
      ## /sensing/imu/001-monitor
      "imu_monitor: yaw_rate_status": default

      ## /sensing/imu/002-connection
      "topic_state_monitor_imu_data: imu_topic_status": default

      ## /sensing/imu/003-gyro_bias
      "gyro_bias_estimator: gyro_bias_validator": default

      # lidar
      ## /sensing/lidar/pndr/001-connection
      "pandar_monitor: /sensing/lidar/front_lower: pandar_connection": default
      "pandar_monitor: /sensing/lidar/front_upper: pandar_connection": default
      "pandar_monitor: /sensing/lidar/left_lower: pandar_connection": default
      "pandar_monitor: /sensing/lidar/left_upper: pandar_connection": default
      "pandar_monitor: /sensing/lidar/right_lower: pandar_connection": default
      "pandar_monitor: /sensing/lidar/right_upper: pandar_connection": default
      "pandar_monitor: /sensing/lidar/rear_lower: pandar_connection": default
      "pandar_monitor: /sensing/lidar/rear_upper: pandar_connection": default

      ## /sensing/lidar/pndr/002-temperature
      "pandar_monitor: /sensing/lidar/front_lower: pandar_temperature": default
      "pandar_monitor: /sensing/lidar/front_upper: pandar_temperature": default
      "pandar_monitor: /sensing/lidar/left_lower: pandar_temperature": default
      "pandar_monitor: /sensing/lidar/left_upper: pandar_temperature": default
      "pandar_monitor: /sensing/lidar/right_lower: pandar_temperature": default
      "pandar_monitor: /sensing/lidar/right_upper: pandar_temperature": default
      "pandar_monitor: /sensing/lidar/rear_lower: pandar_temperature": default
      "pandar_monitor: /sensing/lidar/rear_upper: pandar_temperature": default

      ## /sensing/lidar/pndr/003-ptp
      "pandar_monitor: /sensing/lidar/front_lower: pandar_ptp": default
      "pandar_monitor: /sensing/lidar/front_upper: pandar_ptp": default
      "pandar_monitor: /sensing/lidar/left_lower: pandar_ptp": default
      "pandar_monitor: /sensing/lidar/left_upper: pandar_ptp": default
      "pandar_monitor: /sensing/lidar/right_lower: pandar_ptp": default
      "pandar_monitor: /sensing/lidar/right_upper: pandar_ptp": default
      "pandar_monitor: /sensing/lidar/rear_lower: pandar_ptp": default
      "pandar_monitor: /sensing/lidar/rear_upper: pandar_ptp": default

      ## /sensing/camera/001-connection
      "v4l2_camera_camera0: capture_status": default
      "v4l2_camera_camera1: capture_status": default
      "v4l2_camera_camera2: capture_status": default
      "v4l2_camera_camera3: capture_status": default
      "v4l2_camera_camera4: capture_status": default
      "v4l2_camera_camera5: capture_status": default
      "v4l2_camera_camera6: capture_status": default
      "v4l2_camera_camera7: capture_status": default

      ## /sensing/radar/001-connection
      "radar_monitor: /sensing/radar/front_center: radar_status": default
      "radar_monitor: /sensing/radar/front_left: radar_status": default
      "radar_monitor: /sensing/radar/front_right: radar_status": default
      "radar_monitor: /sensing/radar/rear_center: radar_status": default
      "radar_monitor: /sensing/radar/rear_left: radar_status": default
      "radar_monitor: /sensing/radar/rear_right: radar_status": default

      ## /others/002-blockage_validation
      "blockage_return_diag: /sensing/lidar/front_lower: blockage_validation": default
      "blockage_return_diag: /sensing/lidar/front_upper: blockage_validation": default
      "blockage_return_diag: /sensing/lidar/left_lower: blockage_validation": default
      "blockage_return_diag: /sensing/lidar/left_upper: blockage_validation": default
      "blockage_return_diag: /sensing/lidar/right_lower: blockage_validation": default
      "blockage_return_diag: /sensing/lidar/right_upper: blockage_validation": default
      "blockage_return_diag: /sensing/lidar/rear_lower: blockage_validation": default
      "blockage_return_diag: /sensing/lidar/rear_upper: blockage_validation": default

      ## /others/004-concat_status
      "concatenate_data: concat_status": default

      ## /others/005-visibility_validation/front_lower
      "dual_return_filter: /sensing/lidar/front_lower: visibility_validation": default
      "dual_return_filter: /sensing/lidar/right_upper: visibility_validation": default
