# Description:
#   name: diag name
#   is_active: Force update or not
#   status: diag status set by dummy diag publisher "OK, Warn, Error, Stale"
#
# Note:
#
# default values are:
#   is_active: "true"
#   status: "OK"
---
/**:
  ros__parameters:
    required_diags:
      # gnss
      gnss: default

      # lidar
      pandar_connection: default
      pandar_temperature: default
      pandar_ptp: default
      "left_upper: visibility_validation": default
      blockage_validation: default
      concat_status: default

      sensing_topic_status: default
