sensor_kit_base_link:
  velodyne_top_base_link:
    x: 0.000
    y: 0.000
    z: 0.000
    roll: 0.000
    pitch: 0.000
    yaw: 0.000
  velodyne_front_center_base_link:
    x: 1.130
    y: 0.000
    z: -1.400
    roll: -0.000
    pitch: -0.00
    yaw: 0.000
  tamagawa/imu_link:
    x: -0.500
    y: 0.0
    z: -1.2
    roll: 0.000
    pitch: 0.0
    yaw: 0.0
  gnss_link:
    x: -0.200
    y: 0.0
    z: -0.100
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
